### ISSUE TITLE
Doesn't allow loading of mods...

### ISSUE THREAD

**Issue by GoaTLegend** [ModTheGungeon/Semi#2]
So I've tried getting into semi and making some stuff and trying it out because it seems cool. But when I follow the gitbook guide and do everything right, the game becomes black screen with an error at the main menu... 

`Failed loading mod: [AssemblyResolutionException] Failed to resolve assembly: 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'` 
(I couldn't really see the entire thing on the black screen because the message went past the border of the screen, so this is from the log)

I've tried using the mod template renamed, just as default (altough the YML doesn't contain an api_version at all so I changed that because it said it was missing otherwise), I've also tried renaming the logger identifier name and mod id to no avail. 
All this with reinstalling the game (by deleting everything, the right way) to check that nothing was wrong, on semi and semi-dev branch and all of them gives this same error.

Yes I have .NET Framework 4.5+ and the application targeted to the correct version.
It says the build succeeded in visual studio but there is a warning on the reference to `UnityEngine.CoreModule.dll`. No errors in console. Trying to exchange the dll to one from EtG removes the warning and there are no errors in the console but still gives the same error in the game and in the log.

**Comment by zatherz** [comment]
Your mod has not been built for the correct version as opposed to what you've said. It's been built for 4.0 (hence the error message which says it's trying to load System.Runtime.dll for 4.0). Build for .NET 3.5 as that is the framework version of Mono that Gungeon's build of Unity is using.

**Comment by GoaTLegend** [comment]
I tried targeting 3, 3.5, 4 and 4.5+ all of them give the same error

It says the build succeeded in visual studio but I get multiple of these weird warnings...
`Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3258: The primary reference "MMHOOK_Assembly-CSharp" could not be resolved because it has an indirect dependency on the .NET Framework assembly "System.Data.SqlXml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" which has a higher version "4.0.0.0" than the version "2.0.0.0" in the current target framework`
and
`Microsoft.Common.CurrentVersion.targets(2110,5): warning MSB3268: The primary reference "MMHOOK_Assembly-CSharp" could not be resolved because it has an indirect dependency on the framework assembly "System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" which could not be resolved in the currently targeted framework. ".NETFramework,Version=v3.5". To resolve this problem, either remove the reference "MMHOOK_Assembly-CSharp" or retarget your application to a framework version which contains "System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089".`

**Comment by GoaTLegend** [comment]
I successfully got it to work by not trying to use the mod template at all and referencing everything manually...
