### ISSUE TITLE
im stuck on what to do with mono on mac

### ISSUE THREAD

**Issue by jackdasycho** [ModTheGungeon/Semi#3]

**Comment by jackdasycho** [comment]
i have mono and the installer but it says it cant be opened

**Comment by zatherz** [comment]
This tracker is for the Semi mod loader only, not ETGMod. Semi isn't really for end user use at the moment. If you downloaded it from the website, it says that you get an .exe to open with Mono - that's not actually true (just something I forgot to get rid of). The download is a native binary that you can just run.
